# # oferta_homepage:
# #     path:     /
# #     defaults: { _controller: OfertaBundle:Default:index }

# pagina_estatica:
#     path:  /sitio/{pagina}/
#     defaults:  { _controller: OfertaBundle:Sitio:estatica}

# portada:
#     path: /
#     defaults: { _controller: OfertaBundle:Default:portada }