usuario:
    resource: "@UsuarioBundle/Controller"
    type: annotation
    prefix:   /

tienda:
    resource: "@TiendaBundle/Controller"
    type: annotation
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Controller"
    type: annotation
    prefix:   /

oferta:
    resource: "@OfertaBundle/Controller"
    type: annotation
    prefix:   /
